const TIPOS_AVISO = [
  'comunicado',
  'reunion',
  'evento',
  'obra',
  'corte_servicio',
  'actividad',
  'otro',
]

const TIPOS_INSTITUCION = ['escuela', 'salud', 'comuna', 'organizacion', 'club', 'iglesia', 'otro']

/**
 * Configuración de los módulos: cómo se listan y qué campos se editan.
 * La usa el panel admin y la página "Mis publicaciones", así el formulario
 * genérico (`FormularioModulo`) sirve para todos los módulos.
 */
export const MODULOS = [
  {
    key: 'reclamos',
    label: 'Reclamos',
    icono: 'alerta',
    rutaLista: '/admin/reclamos',
    rutaItem: '/reclamos',
    tipo: 'reclamos',
    columnas: [
      { campo: 'categoria', label: 'Categoría' },
      { campo: 'descripcion', label: 'Descripción' },
      { campo: 'zona', label: 'Zona' },
      { campo: 'estado', label: 'Estado' },
    ],
  },
  {
    key: 'servicios',
    label: 'Servicios',
    icono: 'herramienta',
    rutaLista: '/admin/servicios',
    rutaItem: '/servicios',
    conActivo: true,
    imagen: 'foto_url',
    columnas: [
      { campo: 'titulo', label: 'Título' },
      { campo: 'zona', label: 'Zona' },
      { campo: 'whatsapp', label: 'WhatsApp' },
    ],
    campos: [
      { name: 'titulo', label: 'Título', requerido: true },
      { name: 'descripcion', label: 'Descripción', tipo: 'textarea' },
      { name: 'experiencia', label: 'Experiencia' },
      { name: 'zona', label: 'Zona' },
      { name: 'telefono', label: 'Teléfono' },
      { name: 'whatsapp', label: 'WhatsApp' },
      { name: 'horarios', label: 'Horarios' },
      { name: 'foto_url', label: 'Foto', tipo: 'imagen' },
      { name: 'disponible', label: 'Disponible', tipo: 'checkbox' },
    ],
  },
  {
    key: 'comercios',
    label: 'Comercios',
    icono: 'tienda',
    rutaLista: '/admin/comercios',
    rutaItem: '/comercios',
    conActivo: true,
    imagen: 'logo_url',
    columnas: [
      { campo: 'nombre', label: 'Nombre' },
      { campo: 'descripcion', label: 'Descripción' },
      { campo: 'zona', label: 'Zona' },
      { campo: 'whatsapp', label: 'WhatsApp' },
    ],
    campos: [
      { name: 'nombre', label: 'Nombre', requerido: true },
      { name: 'descripcion', label: 'Descripción', tipo: 'textarea' },
      { name: 'direccion', label: 'Dirección' },
      { name: 'horarios', label: 'Horarios' },
      { name: 'telefono', label: 'Teléfono' },
      { name: 'whatsapp', label: 'WhatsApp' },
      { name: 'zona', label: 'Zona' },
      { name: 'logo_url', label: 'Logo', tipo: 'imagen' },
    ],
  },
  {
    key: 'productores',
    label: 'Productores',
    icono: 'hoja',
    rutaLista: '/admin/productores',
    rutaItem: '/productores',
    conActivo: true,
    columnas: [
      { campo: 'nombre', label: 'Nombre' },
      { campo: 'que_produce', label: 'Produce' },
      { campo: 'que_vende', label: 'Vende' },
      { campo: 'zona', label: 'Zona' },
    ],
    campos: [
      { name: 'nombre', label: 'Nombre', requerido: true },
      { name: 'que_produce', label: 'Qué produce', tipo: 'textarea' },
      { name: 'que_vende', label: 'Qué vende', tipo: 'textarea' },
      { name: 'disponibilidad', label: 'Disponibilidad' },
      { name: 'zona', label: 'Zona' },
      { name: 'telefono', label: 'Teléfono' },
      { name: 'whatsapp', label: 'WhatsApp' },
    ],
  },
  {
    key: 'empleos',
    label: 'Empleo',
    icono: 'maletin',
    rutaLista: '/admin/empleos',
    rutaItem: '/empleos',
    conActivo: true,
    columnas: [
      { campo: 'tipo', label: 'Tipo' },
      { campo: 'titulo', label: 'Título' },
      { campo: 'zona', label: 'Zona' },
      { campo: 'whatsapp', label: 'WhatsApp' },
    ],
    campos: [
      {
        name: 'tipo',
        label: 'Tipo',
        tipo: 'select',
        opciones: [
          ['busco_trabajo', 'Busco trabajo'],
          ['busco_trabajador', 'Busco trabajador'],
        ],
      },
      { name: 'titulo', label: 'Título', requerido: true },
      { name: 'descripcion', label: 'Descripción', tipo: 'textarea' },
      { name: 'experiencia', label: 'Experiencia' },
      { name: 'habilidades', label: 'Habilidades', tipo: 'textarea' },
      { name: 'requisitos', label: 'Requisitos', tipo: 'textarea' },
      { name: 'disponibilidad', label: 'Disponibilidad' },
      { name: 'horario', label: 'Horario' },
      { name: 'zona', label: 'Zona' },
      { name: 'telefono', label: 'Teléfono' },
      { name: 'whatsapp', label: 'WhatsApp' },
    ],
  },
  {
    key: 'instituciones',
    label: 'Instituciones',
    icono: 'edificio',
    rutaLista: '/admin/instituciones',
    rutaItem: '/instituciones',
    crear: true,
    columnas: [
      { campo: 'nombre', label: 'Nombre' },
      { campo: 'tipo', label: 'Tipo' },
      { campo: 'direccion', label: 'Dirección' },
      { campo: 'telefono', label: 'Teléfono' },
    ],
    campos: [
      {
        name: 'tipo',
        label: 'Tipo',
        tipo: 'select',
        opciones: TIPOS_INSTITUCION.map((t) => [t, t]),
      },
      { name: 'nombre', label: 'Nombre', requerido: true },
      { name: 'descripcion', label: 'Descripción', tipo: 'textarea' },
      { name: 'direccion', label: 'Dirección' },
      { name: 'telefono', label: 'Teléfono' },
      { name: 'horarios', label: 'Horarios' },
    ],
  },
  {
    key: 'avisos',
    label: 'Avisos',
    icono: 'megafono',
    rutaLista: '/admin/avisos',
    rutaItem: '/avisos',
    crear: true,
    imagen: 'foto_url',
    columnas: [
      { campo: 'titulo', label: 'Título' },
      { campo: 'tipo', label: 'Tipo' },
      { campo: 'cuerpo', label: 'Texto' },
      { campo: 'fecha_evento', label: 'Fecha' },
    ],
    campos: [
      {
        name: 'tipo',
        label: 'Tipo',
        tipo: 'select',
        opciones: TIPOS_AVISO.map((t) => [t, t]),
      },
      { name: 'titulo', label: 'Título', requerido: true },
      { name: 'cuerpo', label: 'Texto', tipo: 'textarea', requerido: true },
      { name: 'fecha_evento', label: 'Fecha del evento (opcional)', tipo: 'datetime-local' },
      { name: 'foto_url', label: 'Foto (opcional)', tipo: 'imagen' },
    ],
  },
]
